### ISSUE TITLE
'unimplemented' error when using relativeTo: this.activatedRoute

### ISSUE THREAD

**Issue by alexciesielski** [ngrx/router-store#31]
I'm using ngrx/effects in conjunction with router-store and trying to implement a basic navigation effect.

```
constructor(
		private actions$: Actions,
		private route: ActivatedRoute
	) { }

@Effect()
	setActiveStep$: Observable<Action> = this.actions$
		.ofType(actions.ActionTypes.SET_ACTIVE_STEP)
		.map(toPayload)
		.map(step => {
			switch (step) {
				case 1:
					return go(['form', 'products']);

				case 2:
					return go(['form', 'owner']);

				case 3:
					return go(['payment'], { relativeTo: this.route });

				case 4:
					return go(['order'], { relativeTo: this.route });
			}
		});
```

but I am getting `unimplemented` error when activating step 3 or 4.

**Comment by brandonroberts** [comment]
The `ActivatedRoute` is specific to each route component, so its not possible to use it in an effect. If you're dispatching this effect from within your component, you'll have to provide the `ActivatedRoute` from within the component with your dispatched action.

Otherwise you'd have to use the root `ActivatedRoute` and walk down the tree of activated routes to get to the current route.

**Comment by alexciesielski** [comment]
Makes sense, I will pass the activated route in the `payload` then, thanks.
