### ISSUE TITLE
CD does not kickin after go action

### ISSUE THREAD

**Issue by jalalat** [ngrx/router-store#42]
Hi,

I followed the steps (which are very similar to ngrx/router). I had the same issue on ngrx/router as well. Issue is once i submit a go action from my effects like:

@Effect()
    logOffSuccess$: any = this._actions$
        .ofType(ActionTypes.LOGOFF_SUCCESS)
        .map(() => go(['']));

I am successfully taken to home page. Problem is UI kind of frozen in the sense Change detection is not kicking in automatically. Whenever i try to select anything in the UI i can see that in console appropriate function/event is getting invoked. But nothing changes on the UI. If i click something on my keyboard like Ctrl + h (to on/off ngrx tools) CD kicks in and displays the changes i clicked on the UI. After that again no CD kicks in automatically. It is the same with my other effects which are using go action.

No problem with back or forward actions. Only problem with go action.

**Comment by chrisse27** [comment]
Same problem here. Also happens with "replace"

**Comment by brandonroberts** [comment]
Can you reproduce this in a plunker? Here is simple one that's already setup http://plnkr.co/edit/xQcWbyObwXwBrO8XH9hC?p=preview

**Comment by chrisse27** [comment]
We actually figured out yesterday, what the reason was/is: the effect is running due to an action that has been dispatched from within a resolver of a route. During execution of the effect the xhr request fails due to invalid session and a logout action is dispatched which results in another 'replace' action being called. However, nobody told the router that the resolution of the original route actually failed, so the router is happily waiting and blocking the whole UI.

So, currently we are switching from resolvers to canActivate as suggested in https://github.com/ngrx/example-app/blob/master/src/app/guards/book-exists.ts. Note, however, that, CanActivate suffers from the same waiting issue as the resolvers. That's why we changed our waiting code to this:

```
  canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean> {
    return this.store.select(state => state.resolvers) // we're storing information about loaded data here
      .map(state => state.isUserLoaded)
      .do(isUserLoaded => {
        if (!isUserLoaded) {
          this.store.dispatch(new LoadUserAction());
        }
      })
      .filter(isUserLoaded => isUserLoaded)
      .take(1)
      .takeUntil(this.actions$.ofType(ActionTypes.LOAD_USER_FAIL)) // this prevents the UI from being blocked
      .defaultIfEmpty(false);
  }
```

I think that the same issue could also occur in the ngrx example app. If someone starts a navigation on the router outside of book-exists while the CanActivate check is active.
